// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char SSID[]     = SECRET_SSID;    // Network SSID (name)
const char PASS[]     = SECRET_PASS;    // Network password (use for WPA, or use as key for WEP)

void onAirSupplyChange();
void onArmButtonChange();
void onStopButtonChange();
void onTriggerButtonChange();

String messageUpdate;
bool airSupply;
bool armButton;
bool pir_sensor;
bool stopButton;
bool triggerButton;

void initProperties(){

  ArduinoCloud.addProperty(messageUpdate, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(airSupply, READWRITE, ON_CHANGE, onAirSupplyChange);
  ArduinoCloud.addProperty(armButton, READWRITE, ON_CHANGE, onArmButtonChange);
  ArduinoCloud.addProperty(pir_sensor, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(stopButton, READWRITE, ON_CHANGE, onStopButtonChange);
  ArduinoCloud.addProperty(triggerButton, READWRITE, ON_CHANGE, onTriggerButtonChange);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
